from __future__ import annotations
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import Boolean, CheckConstraint, DateTime, ForeignKey, JSON, Numeric, String, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base

def utcnow(): return datetime.now(timezone.utc)
class SuitabilityProfile(Base):
    __tablename__='suitability_profiles'; __table_args__=(UniqueConstraint('project_id','name',name='uq_suitability_profiles_project_name'),)
    id: Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); project_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('projects.id',ondelete='CASCADE'),nullable=False,index=True); created_by_user_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('users.id',ondelete='RESTRICT'),nullable=False); name:Mapped[str]=mapped_column(String(160),nullable=False); description:Mapped[str|None]=mapped_column(Text); review_state:Mapped[str]=mapped_column(String(24),nullable=False,default='unreviewed'); is_archived:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,nullable=False)
class SuitabilityCriterion(Base):
    __tablename__='suitability_criteria'; __table_args__=(CheckConstraint("factor_type IN ('numeric','distance','boolean','categorical','manual_review')",name='suitability_factor_type_valid'),)
    id:Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); profile_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('suitability_profiles.id',ondelete='CASCADE'),nullable=False,index=True); project_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('projects.id',ondelete='CASCADE'),nullable=False,index=True); label:Mapped[str]=mapped_column(String(255),nullable=False); metric_key:Mapped[str]=mapped_column(String(160),nullable=False); factor_type:Mapped[str]=mapped_column(String(24),nullable=False); operator:Mapped[str]=mapped_column(String(24),nullable=False); weight:Mapped[Decimal]=mapped_column(Numeric(8,4),nullable=False); threshold_numeric:Mapped[Decimal|None]=mapped_column(Numeric(24,8)); expected_value:Mapped[str|None]=mapped_column(Text); evidence_source:Mapped[str]=mapped_column(String(32),nullable=False); policy_reference_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('policy_references.id',ondelete='RESTRICT')); compliance_fact_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('compliance_facts.id',ondelete='RESTRICT')); gis_feature_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('gis_features.id',ondelete='RESTRICT')); review_state:Mapped[str]=mapped_column(String(24),nullable=False,default='unreviewed'); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,nullable=False)
class SuitabilityAnalysisRun(Base):
    __tablename__='suitability_analysis_runs'; id:Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); project_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('projects.id',ondelete='CASCADE'),nullable=False,index=True); site_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('sites.id',ondelete='RESTRICT'),nullable=False,index=True); profile_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('suitability_profiles.id',ondelete='RESTRICT'),nullable=False); status:Mapped[str]=mapped_column(String(32),nullable=False); score:Mapped[Decimal|None]=mapped_column(Numeric(8,4)); limitations:Mapped[list]=mapped_column(JSON,nullable=False,default=list); created_by_user_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('users.id',ondelete='RESTRICT'),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,nullable=False)
class SuitabilityCriterionResult(Base):
    __tablename__='suitability_criterion_results'; id:Mapped[uuid.UUID]=mapped_column(Uuid,primary_key=True,default=uuid.uuid4); run_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('suitability_analysis_runs.id',ondelete='CASCADE'),nullable=False,index=True); criterion_id:Mapped[uuid.UUID]=mapped_column(Uuid,ForeignKey('suitability_criteria.id',ondelete='RESTRICT'),nullable=False); status:Mapped[str]=mapped_column(String(32),nullable=False); normalized_score:Mapped[Decimal|None]=mapped_column(Numeric(8,4)); evidence:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict); compliance_fact_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('compliance_facts.id',ondelete='SET NULL')); gis_feature_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('gis_features.id',ondelete='SET NULL')); policy_reference_id:Mapped[uuid.UUID|None]=mapped_column(Uuid,ForeignKey('policy_references.id',ondelete='SET NULL')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,nullable=False)
